data_dir = "/usr/local/share/ckb/nodes/node1"

[db]
path = "db"

[chain]
spec = "/usr/local/share/ckb/nodes/node1/spec/dev.toml"

[logger]
file = "ckb.log"
filter = "info,chain=debug,network=debug"
color = true

[network]
path = "/usr/local/share/ckb/nodes/node1/network"
listen_addresses = ["/ip4/0.0.0.0/tcp/8115"]
public_addresses = []
bootnodes = []
reserved_peers = []
reserved_only = false
max_peers = 125
max_outbound_peers = 30
ping_interval_secs = 15
ping_timeout_secs = 20
connect_outbound_interval_secs = 15

[rpc]
listen_address = "0.0.0.0:8114"

# Default is 10MiB = 10 * 1024 * 1024
max_request_body_size = 10485760

# List of API modules: ["Net", "Pool", "Miner", "Chain", "Trace"]
modules = ["Net", "Pool", "Miner", "Chain"]

[sync]
verification_level = "Full"
orphan_block_limit = 1024

[tx_pool]
max_pool_size = 10000
max_orphan_size = 10000
max_proposal_size = 10000
max_cache_size = 1000
max_pending_size = 10000
trace = 100
txs_verify_cache_size = 100000

[block_assembler]
type_hash = "0x8954a4ac5e5c33eb7aa8bb91e0a000179708157729859bd8cf7e2278e1e12980"
